-- Metis v0.1 database schema
-- Run this in Supabase Dashboard: SQL Editor -> New query

create extension if not exists "pgcrypto";

-- User profile linked to Supabase Auth
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  exam_type text not null default 'cet4',
  exam_date date,
  daily_minutes integer not null default 30,
  streak_days integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Initial assessment result
create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  level text not null,
  vocabulary_score integer,
  grammar_score integer,
  listening_score integer,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- One AI-generated plan per user per day
create table if not exists public.daily_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_date date not null default current_date,
  total_minutes integer not null default 0,
  status text not null default 'pending',
  generated_by text not null default 'ai',
  created_at timestamptz not null default now(),
  unique (user_id, plan_date)
);

-- Tasks inside a daily plan
create table if not exists public.daily_tasks (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.daily_plans(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  task_type text not null,
  title text not null,
  payload jsonb not null default '{}'::jsonb,
  estimated_minutes integer not null default 0,
  status text not null default 'pending',
  order_index integer not null default 0,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Curated vocabulary content, not generated by AI
create table if not exists public.words (
  id uuid primary key default gen_random_uuid(),
  word text not null unique,
  phonetic text,
  meaning text not null,
  example text,
  difficulty integer not null default 1,
  source text,
  tags text[] not null default '{}'
);

-- Spaced repetition state per user
create table if not exists public.user_word_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  word_id uuid not null references public.words(id) on delete cascade,
  status text not null default 'new',
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  next_review_at timestamptz,
  last_reviewed_at timestamptz,
  primary key (user_id, word_id)
);

-- Daily check-in and streak source
create table if not exists public.check_ins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  check_date date not null default current_date,
  completed_count integer not null default 0,
  total_count integer not null default 0,
  total_focus_minutes integer not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, check_date)
);

create index if not exists daily_tasks_user_date_idx
  on public.daily_tasks (user_id, created_at);

create index if not exists user_word_progress_review_idx
  on public.user_word_progress (user_id, next_review_at);
