-- Metis 首批四六级高频词 seed 数据
-- 在 Supabase SQL Editor 中运行一次即可

insert into public.words (word, phonetic, meaning, example, difficulty, tags) values
  ('abandon', '/əˈbændən/', 'v. 放弃；抛弃', 'He decided to abandon the old plan.', 1, '{cet4,verb}'),
  ('ability', '/əˈbɪləti/', 'n. 能力；才能', 'She has the ability to solve problems quickly.', 1, '{cet4,noun}'),
  ('absorb', '/əbˈzɔːb/', 'v. 吸收；吸引', 'Plants absorb water through their roots.', 1, '{cet4,verb}'),
  ('academic', '/ˌækəˈdemɪk/', 'adj. 学术的；学院的', 'Academic success requires consistent effort.', 1, '{cet4,adjective}'),
  ('access', '/ˈækses/', 'n. 通道；使用权 v. 访问', 'Students have free access to the library.', 1, '{cet4,noun,verb}'),
  ('accompany', '/əˈkʌmpəni/', 'v. 陪伴；伴随', 'Lightning is often accompanied by thunder.', 2, '{cet4,verb}'),
  ('achieve', '/əˈtʃiːv/', 'v. 达到；实现', 'You can achieve your goal with practice.', 1, '{cet4,verb}'),
  ('acknowledge', '/əkˈnɒlɪdʒ/', 'v. 承认；致谢', 'He acknowledged his mistake immediately.', 2, '{cet6,verb}'),
  ('acquire', '/əˈkwaɪə/', 'v. 获得；习得', 'Children acquire language naturally.', 2, '{cet4,verb}'),
  ('adapt', '/əˈdæpt/', 'v. 适应；改编', 'The species adapted to the cold climate.', 2, '{cet4,verb}'),
  ('adequate', '/ˈædɪkwət/', 'adj. 足够的；适当的', 'The room provides adequate space for study.', 2, '{cet4,adjective}'),
  ('adjust', '/əˈdʒʌst/', 'v. 调整；适应', 'Please adjust the volume to a comfortable level.', 1, '{cet4,verb}'),
  ('admire', '/ədˈmaɪə/', 'v. 钦佩；欣赏', 'I admire her courage and honesty.', 1, '{cet4,verb}'),
  ('advocate', '/ˈædvəkeɪt/', 'v. 提倡 n. 拥护者', 'Many experts advocate regular exercise.', 3, '{cet6,verb,noun}'),
  ('afford', '/əˈfɔːd/', 'v. 负担得起；提供', 'We cannot afford to waste time.', 1, '{cet4,verb}'),
  ('alternative', '/ɔːlˈtɜːnətɪv/', 'n. 替代方案 adj. 可替代的', 'We need an alternative to this method.', 2, '{cet4,noun,adjective}'),
  ('analyze', '/ˈænəlaɪz/', 'v. 分析', 'The report analyzes the latest market trends.', 2, '{cet4,verb}'),
  ('anticipate', '/ænˈtɪsɪpeɪt/', 'v. 预期；预料', 'We anticipate a rise in demand.', 3, '{cet6,verb}'),
  ('apparent', '/əˈpærənt/', 'adj. 明显的；表面的', 'It was apparent that she was tired.', 2, '{cet4,adjective}'),
  ('approach', '/əˈprəʊtʃ/', 'n. 方法 v. 接近', 'A new approach to teaching works well.', 1, '{cet4,noun,verb}'),
  ('appropriate', '/əˈprəʊpriət/', 'adj. 适当的', 'Choose appropriate words for the occasion.', 2, '{cet4,adjective}'),
  ('assess', '/əˈses/', 'v. 评估；评价', 'Teachers assess students progress regularly.', 2, '{cet6,verb}'),
  ('assign', '/əˈsaɪn/', 'v. 分配；指派', 'The teacher assigned homework to the class.', 2, '{cet4,verb}'),
  ('assume', '/əˈsjuːm/', 'v. 假定；承担', 'We assume that the plan will work.', 2, '{cet4,verb}'),
  ('available', '/əˈveɪləbl/', 'adj. 可用的；可获得的', 'The data is available online.', 1, '{cet4,adjective}'),
  ('benefit', '/ˈbenɪfɪt/', 'n. 好处 v. 受益', 'Regular reading brings many benefits.', 1, '{cet4,noun,verb}'),
  ('challenge', '/ˈtʃælɪndʒ/', 'n. 挑战 v. 质疑', 'Learning a new language is a challenge.', 1, '{cet4,noun,verb}'),
  ('comprehensive', '/ˌkɒmprɪˈhensɪv/', 'adj. 全面的；综合的', 'The report gives a comprehensive review.', 3, '{cet6,adjective}'),
  ('concept', '/ˈkɒnsept/', 'n. 概念；观念', 'The concept of time is difficult to define.', 2, '{cet4,noun}'),
  ('consequence', '/ˈkɒnsɪkwəns/', 'n. 后果；结果', 'Every choice has its consequences.', 2, '{cet6,noun}'),
  ('consume', '/kənˈsjuːm/', 'v. 消耗；消费', 'The engine consumes a lot of fuel.', 2, '{cet6,verb}'),
  ('contribute', '/kənˈtrɪbjuːt/', 'v. 贡献；促成', 'Everyone can contribute to the team.', 2, '{cet4,verb}'),
  ('crucial', '/ˈkruːʃl/', 'adj. 关键的；至关重要的', 'Timing is crucial to the success of the project.', 3, '{cet6,adjective}'),
  ('demonstrate', '/ˈdemənstreɪt/', 'v. 证明；演示', 'The study demonstrates the effect clearly.', 2, '{cet4,verb}'),
  ('distinguish', '/dɪˈstɪŋɡwɪʃ/', 'v. 区分；辨别', 'It is hard to distinguish the two colors.', 2, '{cet6,verb}'),
  ('eliminate', '/ɪˈlɪmɪneɪt/', 'v. 消除；淘汰', 'We should eliminate unnecessary steps.', 3, '{cet6,verb}'),
  ('emphasize', '/ˈemfəsaɪz/', 'v. 强调', 'The teacher emphasized the importance of review.', 2, '{cet4,verb}'),
  ('enhance', '/ɪnˈhɑːns/', 'v. 提高；增强', 'Music can enhance the learning experience.', 3, '{cet6,verb}'),
  ('essential', '/ɪˈsenʃl/', 'adj. 必要的；本质的', 'Water is essential for all living things.', 2, '{cet4,adjective}'),
  ('evaluate', '/ɪˈvæljueɪt/', 'v. 评估；评价', 'We evaluate the results every month.', 2, '{cet4,verb}');
