insert into public.words (word, phonetic, meaning, example, difficulty, tags) values
  ('evidence', '/ˈevɪdəns/', 'n. 证据；迹象', 'There is clear evidence that exercise improves memory.', 2, '{cet4,noun}'),
  ('expand', '/ɪkˈspænd/', 'v. 扩大；扩展', 'The company plans to expand its business overseas.', 2, '{cet4,verb}'),
  ('factor', '/ˈfæktə/', 'n. 因素；要素', 'Cost is an important factor in the decision.', 1, '{cet4,noun}'),
  ('feature', '/ˈfiːtʃə/', 'n. 特点 v. 以...为特色', 'The new phone features a larger screen.', 2, '{cet4,noun,verb}'),
  ('flexible', '/ˈfleksəbl/', 'adj. 灵活的；可变通的', 'A flexible schedule helps students balance study and life.', 2, '{cet4,adjective}'),
  ('focus', '/ˈfəʊkəs/', 'v. 集中 n. 焦点', 'Try to focus on one task at a time.', 1, '{cet4,verb,noun}'),
  ('generate', '/ˈdʒenəreɪt/', 'v. 产生；引起', 'The project generated a lot of public interest.', 2, '{cet6,verb}'),
  ('global', '/ˈɡləʊbl/', 'adj. 全球的；整体的', 'Climate change is a global challenge.', 1, '{cet4,adjective}'),
  ('identify', '/aɪˈdentɪfaɪ/', 'v. 识别；确认', 'Scientists identified the cause of the disease.', 1, '{cet4,verb}'),
  ('ignore', '/ɪɡˈnɔː/', 'v. 忽视；不理会', 'You cannot ignore the importance of sleep.', 1, '{cet4,verb}'),
  ('impact', '/ˈɪmpækt/', 'n. 影响 v. 冲击', 'Technology has a huge impact on education.', 2, '{cet4,noun,verb}'),
  ('imply', '/ɪmˈplaɪ/', 'v. 暗示；意味着', 'The report implies that sales may fall.', 3, '{cet6,verb}'),
  ('individual', '/ˌɪndɪˈvɪdʒuəl/', 'adj. 个人的 n. 个人', 'Each individual learns at a different pace.', 2, '{cet4,adjective,noun}'),
  ('influence', '/ˈɪnfluəns/', 'n. 影响 v. 影响', 'Friends can influence our habits.', 1, '{cet4,noun,verb}'),
  ('insist', '/ɪnˈsɪst/', 'v. 坚持；坚决要求', 'She insisted on paying for the meal.', 2, '{cet4,verb}'),
  ('involve', '/ɪnˈvɒlv/', 'v. 涉及；包含', 'The job involves a lot of travel.', 1, '{cet4,verb}'),
  ('maintain', '/meɪnˈteɪn/', 'v. 保持；维护', 'Regular exercise helps maintain good health.', 2, '{cet4,verb}'),
  ('major', '/ˈmeɪdʒə/', 'adj. 主要的 n. 专业', 'English is her major in college.', 1, '{cet4,adjective,noun}'),
  ('method', '/ˈmeθəd/', 'n. 方法；办法', 'This teaching method works well for beginners.', 1, '{cet4,noun}'),
  ('obtain', '/əbˈteɪn/', 'v. 获得；得到', 'Students can obtain more information online.', 2, '{cet4,verb}'),
  ('obvious', '/ˈɒbviəs/', 'adj. 明显的', 'It is obvious that he was nervous.', 1, '{cet4,adjective}'),
  ('occur', '/əˈkɜː/', 'v. 发生；出现', 'The accident occurred late at night.', 2, '{cet4,verb}'),
  ('opportunity', '/ˌɒpəˈtjuːnəti/', 'n. 机会；时机', 'College provides many opportunities to grow.', 1, '{cet4,noun}'),
  ('participate', '/pɑːˈtɪsɪpeɪt/', 'v. 参加；参与', 'All students are encouraged to participate.', 2, '{cet4,verb}'),
  ('particular', '/pəˈtɪkjələ/', 'adj. 特定的；特别的', 'Is there any particular reason for your choice?', 2, '{cet4,adjective}'),
  ('perceive', '/pəˈsiːv/', 'v. 察觉；理解', 'People perceive the same event differently.', 3, '{cet6,verb}'),
  ('potential', '/pəˈtenʃl/', 'n. 潜力 adj. 潜在的', 'The child shows great potential in music.', 2, '{cet4,noun,adjective}'),
  ('precise', '/prɪˈsaɪs/', 'adj. 精确的；准确的', 'Please give a precise description.', 2, '{cet6,adjective}'),
  ('predict', '/prɪˈdɪkt/', 'v. 预测；预言', 'It is hard to predict the weather accurately.', 2, '{cet4,verb}'),
  ('previous', '/ˈpriːviəs/', 'adj. 先前的；以往的', 'He had met her on a previous occasion.', 1, '{cet4,adjective}'),
  ('primary', '/ˈpraɪməri/', 'adj. 主要的；初级的', 'The primary goal is to reduce costs.', 2, '{cet4,adjective}'),
  ('principle', '/ˈprɪnsəpl/', 'n. 原则；原理', 'He refused to give up his principles.', 2, '{cet4,noun}'),
  ('process', '/ˈprəʊses/', 'n. 过程 v. 处理', 'Learning is a long process.', 1, '{cet4,noun,verb}'),
  ('pursue', '/pəˈsjuː/', 'v. 追求；从事', 'She decided to pursue a career in medicine.', 2, '{cet6,verb}'),
  ('relevant', '/ˈreləvənt/', 'adj. 相关的；切题的', 'Keep your answer relevant to the question.', 2, '{cet4,adjective}'),
  ('reliable', '/rɪˈlaɪəbl/', 'adj. 可靠的；可信赖的', 'We need a reliable source of information.', 2, '{cet4,adjective}'),
  ('require', '/rɪˈkwaɪə/', 'v. 需要；要求', 'The task requires patience and care.', 1, '{cet4,verb}'),
  ('respond', '/rɪˈspɒnd/', 'v. 回答；回应', 'She responded quickly to my message.', 1, '{cet4,verb}'),
  ('significant', '/sɪɡˈnɪfɪkənt/', 'adj. 重要的；显著的', 'There was a significant improvement in his grades.', 2, '{cet4,adjective}'),
  ('specific', '/spəˈsɪfɪk/', 'adj. 具体的；特定的', 'Can you give a specific example?', 1, '{cet4,adjective}'),
  ('strategy', '/ˈstrætədʒi/', 'n. 策略；战略', 'A good strategy can save time and effort.', 2, '{cet4,noun}'),
  ('sufficient', '/səˈfɪʃnt/', 'adj. 足够的；充分的', 'We have sufficient time to finish the task.', 2, '{cet6,adjective}'),
  ('survey', '/ˈsɜːveɪ/', 'n. 调查；测量', 'The survey shows a rise in online learning.', 2, '{cet4,noun,verb}'),
  ('sustain', '/səˈsteɪn/', 'v. 维持；支撑', 'It is difficult to sustain attention for hours.', 3, '{cet6,verb}'),
  ('transform', '/trænsˈfɔːm/', 'v. 改变；转变', 'The internet has transformed daily life.', 2, '{cet6,verb}'),
  ('trend', '/trend/', 'n. 趋势；倾向', 'There is a growing trend toward remote work.', 2, '{cet4,noun}'),
  ('ultimate', '/ˈʌltɪmət/', 'adj. 最终的；根本的', 'The ultimate goal of education is to develop minds.', 2, '{cet6,adjective}'),
  ('unique', '/juːˈniːk/', 'adj. 独特的；唯一的', 'Each person has a unique way of learning.', 1, '{cet4,adjective}'),
  ('vary', '/ˈveəri/', 'v. 变化；不同', 'Prices vary from store to store.', 2, '{cet4,verb}'),
  ('virtual', '/ˈvɜːtʃuəl/', 'adj. 虚拟的；实际上的', 'Many classes are now held in virtual classrooms.', 2, '{cet6,adjective}'),
  ('visible', '/ˈvɪzəbl/', 'adj. 可见的；明显的', 'The stars are clearly visible tonight.', 1, '{cet4,adjective}'),
  ('widespread', '/ˈwaɪdspred/', 'adj. 广泛的；普遍的', 'The use of smartphones is widespread among students.', 2, '{cet6,adjective}'),
  ('accomplish', '/əˈkʌmplɪʃ/', 'v. 完成；实现', 'She accomplished more than expected this year.', 2, '{cet6,verb}'),
  ('accurate', '/ˈækjərət/', 'adj. 准确的；精确的', 'The test provides accurate results.', 2, '{cet4,adjective}'),
  ('adaptable', '/əˈdæptəbl/', 'adj. 能适应的', 'Successful learners are highly adaptable.', 3, '{cet6,adjective}'),
  ('advance', '/ədˈvɑːns/', 'v. 前进 n. 进步', 'Technology continues to advance rapidly.', 1, '{cet4,verb,noun}'),
  ('allocate', '/ˈæləkeɪt/', 'v. 分配；拨给', 'We must allocate time wisely.', 3, '{cet6,verb}'),
  ('ambition', '/æmˈbɪʃn/', 'n. 雄心；抱负', 'Her ambition is to become a scientist.', 2, '{cet4,noun}'),
  ('appreciate', '/əˈpriːʃieɪt/', 'v. 欣赏；感激', 'I appreciate your help.', 1, '{cet4,verb}'),
  ('associate', '/əˈsəʊʃieɪt/', 'v. 联想；联系', 'People often associate red with danger.', 2, '{cet4,verb}')
  on conflict (word) do nothing;
