-- Metis 首批阅读材料 seed 数据
-- 文章为原创的通用题材短文，题目为原创，避免版权风险

insert into public.passages (id, title, content, difficulty, source, tags) values
  ('11111111-1111-1111-1111-111111111111',
   'The Value of Sleep',
   'For many students, sleep is the first thing to be sacrificed when deadlines approach. Staying up late may feel productive, but research shows the opposite. During deep sleep, the brain strengthens memories and organizes new information. Without enough rest, attention drops, problem-solving slows, and emotions become harder to control. Experts recommend seven to nine hours of sleep for young adults. A short nap in the afternoon can also restore energy, but it should not last more than thirty minutes. Building a regular sleep schedule is a simple habit that improves both learning and health.',
   1,
   'original',
   '{cet4,science}'),
  ('22222222-2222-2222-2222-222222222222',
   'Learning a Second Language',
   'Learning a second language is not only useful for travel or work; it also changes the way the brain works. Studies show that bilingual people are often better at switching between tasks and ignoring distractions. The process of remembering words in two languages strengthens mental flexibility. Age matters, but it is not everything. Adults can still become fluent, though they may learn more slowly than children in some areas. The key is regular practice rather than occasional hard work. Even fifteen minutes a day, continued over months, can produce clear progress.',
   2,
   'original',
   '{cet4,education}'),
  ('33333333-3333-3333-3333-333333333333',
   'The Rise of Remote Work',
   'Remote work has grown quickly in recent years, and many companies now allow employees to work from home several days a week. Supporters say this reduces commuting time and gives workers more freedom. Critics, however, point out that communication can become slower and that some employees feel isolated. To make remote work successful, companies need clear rules, regular online meetings, and trust in their teams. For workers, a separate office space at home and a fixed daily schedule help keep life and work in balance. Remote work is unlikely to disappear, but the way it is organized will keep changing.',
   2,
   'original',
   '{cet6,society}');

insert into public.questions (id, passage_id, question, options, correct_index, explanation, order_index) values
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111',
   'What is the main idea of the passage?',
   '["Sleep is less important than study", "Sleep improves learning and health", "Students should avoid afternoon naps", "Adults need more sleep than children"]',
   1,
   '文章反复强调睡眠对记忆、注意力和情绪的作用，最后落到对学习和健康的好处。',
   0),
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111',
   'How long should an afternoon nap last?',
   '["No more than 30 minutes", "At least one hour", "Two hours or more", "The whole afternoon"]',
   0,
   '原文明确说午睡不应超过三十分钟。',
   1),
  (gen_random_uuid(), '22222222-2222-2222-2222-222222222222',
   'What advantage do bilingual people often have?',
   '["They never get distracted", "They switch tasks more easily", "They learn all languages faster", "They remember every word"]',
   1,
   '第二句提到双语者在切换任务和忽略干扰方面通常更强。',
   0),
  (gen_random_uuid(), '22222222-2222-2222-2222-222222222222',
   'According to the passage, what matters most in learning a language?',
   '["Starting as a child", "Occasional hard work", "Regular practice", "Living abroad"]',
   2,
   '文章末尾强调关键是规律练习，而不是偶尔的刻苦。',
   1),
  (gen_random_uuid(), '33333333-3333-3333-3333-333333333333',
   'What is one problem of remote work mentioned in the passage?',
   '["Employees feel isolated", "Commuting time increases", "Office costs rise", "Workers have less freedom"]',
   0,
   '批评者指出沟通变慢、部分员工感到孤立。',
   0);
