insert into public.passages (id, title, content, difficulty, source, tags) values
  ('44444444-4444-4444-4444-444444444444', 'The Power of Reading', 'Reading is one of the most effective ways to improve language skills. When people read regularly, they meet new words in natural contexts, which helps them remember meanings more easily. Reading also exposes learners to different sentence structures and writing styles. It is not necessary to read difficult books from the start. Short articles, stories, and news reports are all useful materials. The key is to choose something that is neither too easy nor too hard, so that learning stays interesting and challenging at the same time.',
   1, 'original', '{cet4,education}'),
  ('55555555-5555-5555-5555-555555555555', 'The Importance of Failure', 'Many people fear failure and try to avoid it at all costs. However, failure is often a necessary part of growth. When we make mistakes, we learn what does not work and can adjust our approach. Successful people usually experience failure many times before reaching their goals. What matters is not how many times we fall, but whether we are willing to get up and try again. A healthy attitude toward failure can turn disappointment into a valuable lesson.',
   2, 'original', '{cet4,psychology}'),
  ('66666666-6666-6666-6666-666666666666', 'Cities and Green Spaces', 'As cities grow larger, green spaces such as parks and gardens become increasingly important. Trees and plants help clean the air and reduce city temperatures. Green spaces also give people a place to relax, exercise, and meet others. However, land in cities is often limited and expensive, so planners must find creative ways to include nature. Some cities have turned old railways and empty rooftops into gardens. These efforts show that green spaces can be added even in crowded places.',
   2, 'original', '{cet6,environment}');

insert into public.questions (passage_id, question, options, correct_index, explanation, order_index) values
  ('44444444-4444-4444-4444-444444444444', 'Why is reading effective for language learning?', '["It is the only way to learn", "Words appear in natural contexts", "It requires no effort", "It avoids all difficulties"]', 1, 'The passage says new words are met in natural contexts, which helps memory.', 0),
  ('44444444-4444-4444-4444-444444444444', 'What kind of material should learners choose?', '["Only difficult books", "Only simple stories", "Something neither too easy nor too hard", "Only news reports"]', 2, 'The ending advises choosing material that is neither too easy nor too hard.', 1),
  ('55555555-5555-5555-5555-555555555555', 'What is the main idea of the passage?', '["Failure should be avoided", "Failure can help us grow", "Successful people never fail", "Mistakes are always costly"]', 1, 'The passage argues that failure is a necessary part of growth.', 0),
  ('55555555-5555-5555-5555-555555555555', 'What matters most after failing, according to the passage?', '["How often we fall", "Whether we try again", "How others judge us", "How big the mistake was"]', 1, 'It says what matters is whether we get up and try again.', 1),
  ('66666666-6666-6666-6666-666666666666', 'What is one benefit of green spaces mentioned?', '["They increase city temperatures", "They provide places to relax", "They make land cheaper", "They reduce the need for parks"]', 1, 'Green spaces give people a place to relax, exercise, and meet others.', 0),
  ('66666666-6666-6666-6666-666666666666', 'How have some cities added green spaces?', '["By removing all buildings", "By using old railways and rooftops", "By building more roads", "By expanding parking lots"]', 1, 'The passage says old railways and empty rooftops were turned into gardens.', 1);
